Omer Afzal's Portfolio
omer-creator/Portfolio pull request #1
Opened 2023-01-12 22:49 UTC by omer-creator

This is my personal Portfolio.

2023-01-13 01:01 UTC, AbayomiOlaoye requested changes
Hi @omer-creator 👋 , 

Good job with this milestone so far!
There are just few more issues to work on before moving onto the next project but you are almost there!

![so_close](https://user-images.githubusercontent.com/99715640/211950260-0e3881c0-9d4f-4ea2-a670-9ef45a23a0f5.gif)

## Highlights
- Descriptive Pull Request message :heavy_check_mark: 
- Good use of GitHub flow :heavy_check_mark: 
- Meaningful commit messages :heavy_check_mark: 
- No linter error :heavy_check_mark: 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-14 10:30 UTC, omer-creator commented on README.md
> +</div>
Image logo has been added

2023-01-14 10:32 UTC, omer-creator commented on README.md
> +**portfolio_microverse** is a portfolio
Commented lines removed and edited README template in a more decriptive statements.

2023-01-14 10:32 UTC, omer-creator commented on README.md
> +> We use html,css(flexbox,grid) to convert ui from figma to html,css.
Commented lines removed

2023-01-14 10:32 UTC, omer-creator commented on README.md
> +  </ul>
Readme template edited according to the project.

2023-01-14 10:33 UTC, omer-creator commented on README.md
> +> Describe between 1-3 key features of the application.
Commented lines removed

2023-01-14 10:33 UTC, omer-creator commented on README.md
> +  - [Answer_2]
Unused content removed.

2023-01-14 10:34 UTC, omer-creator commented on index.html
> +        </header>
Overlapping content fixed.

2023-01-14 10:34 UTC, omer-creator commented on index.html
> +                    <p class="Subhead welcome-text">Welcome to my Portfolio</p>
Typo Fixed.

2023-01-14 10:35 UTC, omer-creator commented on index.html
> +            </ul>
Added two more social media content links

2023-01-14 10:36 UTC, omer-creator commented on index.html
> +        </section>
All suggested and required change completed.

2023-01-14 12:45 UTC, didierganthier reviewed
Hi @omer-creator ,

While you put in a lot of hard work in this project, unfortunately, I cannot proceed with the review of your code.

<img src="https://media.giphy.com/media/d2lcHJTG5Tscg/giphy.gif" />

## Invalid Code Review Request 🚫

- You have submitted a project with the StyLelint (linters) test not passing 😢 

Your Code Review Request will be marked as invalid in your Dashboard, but don't worry you can always try again! 💪

Cheers and Happy coding!👏👏👏

If you have any questions or need clarification on anything, feel free to leave a comment in the pull request thread and don't forget to tag me so I'll receive the notification.

**Please note**
- To avoid confusion and delays, please do not open a new pull request for re-reviews. Use the same pull request submitted for the first review, unless otherwise instructed.

--------

_Invalid Code Review Request **does not count** towards the code reviews limit._

2023-01-14 13:12 UTC, christianbiring1 approved these changes
Hi @omer-creator , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
# STATUS: APPROVED :tada: 
![congraaaa](https://user-images.githubusercontent.com/97100091/212473245-24729c4f-78ec-423d-aced-591e63b1c2e3.gif)

## Highlights
- [ ] All linters checks are green :heavy_check_mark: 
- [ ] Good looking UI :art: 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-14 13:20 UTC, merged